//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCVCapitalIntrant.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cvcxcapital_sysdataEntities : DbContext
    {
        public cvcxcapital_sysdataEntities()
            : base("name=cvcxcapital_sysdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_userinfo_base> t_userinfo_base { get; set; }
        public virtual DbSet<t_user_edu> t_user_edu { get; set; }
        public virtual DbSet<t_user_relation> t_user_relation { get; set; }
        public virtual DbSet<t_user_resume> t_user_resume { get; set; }
        public virtual DbSet<t_user_branchchange> t_user_branchchange { get; set; }
        public virtual DbSet<t_user_deptchange> t_user_deptchange { get; set; }
        public virtual DbSet<t_user_levelchange> t_user_levelchange { get; set; }
        public virtual DbSet<t_user_picchange> t_user_picchange { get; set; }
        public virtual DbSet<t_user_postchange> t_user_postchange { get; set; }
        public virtual DbSet<t_user_secretarychange> t_user_secretarychange { get; set; }
        public virtual DbSet<t_user_titlechange> t_user_titlechange { get; set; }
    }
}
