//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCVCapitalIntrant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_edu
    {
        public int pkid { get; set; }
        public int userid { get; set; }
        public string university { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> education { get; set; }
        public string major { get; set; }
        public string desc { get; set; }
        public System.DateTime updatetime { get; set; }
        public int updateuserid { get; set; }
    }
}
