//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCVCapitalIntrant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_relation
    {
        public int pkid { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> nationalityid { get; set; }
        public string nation { get; set; }
        public int relationship { get; set; }
        public Nullable<int> location { get; set; }
        public string company { get; set; }
        public string occupation { get; set; }
        public string post { get; set; }
        public string isparty { get; set; }
        public string desc { get; set; }
    }
}
