//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCVCapitalIntrant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_resume
    {
        public int okid { get; set; }
        public int userid { get; set; }
        public string belcompany { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string lasttitle { get; set; }
        public string lastjobpost { get; set; }
        public string lastlevel { get; set; }
        public Nullable<int> salary { get; set; }
        public string reporttoleader { get; set; }
        public string leadertitle { get; set; }
        public string leaderlevel { get; set; }
        public string dutydesc { get; set; }
        public System.DateTime updatetime { get; set; }
        public int updateuserid { get; set; }
    }
}
