//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCVCapitalIntrant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_userinfo_base
    {
        public int pkid { get; set; }
        public string usercode { get; set; }
        public string pycodefull { get; set; }
        public string pycodeshort { get; set; }
        public string usernameen { get; set; }
        public string nickname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> birthcountry { get; set; }
        public Nullable<int> birthcity { get; set; }
        public Nullable<int> nationalityid { get; set; }
        public Nullable<int> lastrecord { get; set; }
        public string lastschool { get; set; }
        public string lastspeciality { get; set; }
        public Nullable<System.DateTime> lastschooldate { get; set; }
        public Nullable<System.DateTime> checkindate { get; set; }
        public Nullable<System.DateTime> checkoutdate { get; set; }
        public byte[] userhrpic { get; set; }
        public string userhrpictype { get; set; }
        public byte[] userselfpic { get; set; }
        public string userselfpictype { get; set; }
        public Nullable<int> lasttitle { get; set; }
        public Nullable<int> lastjobpost { get; set; }
        public Nullable<int> lastlevel { get; set; }
        public Nullable<int> costcenterid { get; set; }
        public Nullable<int> basecityid { get; set; }
        public Nullable<int> workcityid { get; set; }
        public Nullable<int> towerid { get; set; }
        public string officenum { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> subcomid { get; set; }
        public Nullable<int> departid { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<int> secuserid1 { get; set; }
        public Nullable<int> secuserid2 { get; set; }
        public string phonenums { get; set; }
        public string callnums { get; set; }
        public string faxnums { get; set; }
        public string emailcom { get; set; }
        public string emailself { get; set; }
        public Nullable<int> politicalid { get; set; }
        public Nullable<System.DateTime> inpartydate { get; set; }
        public Nullable<System.DateTime> lastlogdate { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> isdeleted { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> updateuserid { get; set; }
    }
}
